"use client";

import { useState } from "react";
import { AreaChart, Area, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, BarChart, Bar, PieChart, Pie, Cell, Legend } from "recharts";
import { Download, AlertTriangle, CheckCircle, Clock, ShieldAlert, FileText, Filter } from "lucide-react";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

// --- MOCK DATA ---
const dataTrend = [
    { time: "08:00", score: 98 }, { time: "09:00", score: 95 },
    { time: "10:00", score: 88 }, { time: "11:00", score: 92 },
    { time: "12:00", score: 96 }, { time: "13:00", score: 90 },
    { time: "14:00", score: 85 }, { time: "15:00", score: 94 },
];

const dataViolation = [
    { name: "No Helmet", count: 12 },
    { name: "No Vest", count: 8 },
    { name: "Unsafe Zone", count: 5 },
    { name: "No Gloves", count: 3 },
];

const dataZone = [
    { name: "Safe Zone", value: 75, color: "#10b981" },
    { name: "Warning Zone", value: 20, color: "#f59e0b" },
    { name: "Critical Zone", value: 5, color: "#ef4444" },
];

const historyData = [
    { id: "ALRT-001", time: "14:30", location: "Zone A - Loading", type: "No Helmet", status: "Open" },
    { id: "ALRT-002", time: "13:15", location: "Zone B - Welding", type: "No Gloves", status: "Resolved" },
    { id: "ALRT-003", time: "11:45", location: "Zone C - Chemical", type: "Unsafe Zone", status: "Resolved" },
    { id: "ALRT-004", time: "10:20", location: "Zone A - Loading", type: "No Vest", status: "Resolved" },
    { id: "ALRT-005", time: "09:10", location: "Zone D - Storage", type: "No Helmet", status: "Open" },
];

export default function AnalyticsPage() {
    const [isGenerating, setIsGenerating] = useState(false);

    // --- FUNGSI DOWNLOAD PDF ---
    const handleDownloadPDF = () => {
        setIsGenerating(true);
        const doc = new jsPDF();

        // 1. Header Laporan
        doc.setFontSize(18);
        doc.text("SMARTAPD - SAFETY AUDIT REPORT", 14, 20);
        doc.setFontSize(10);
        doc.text(`Generated by AI System | Date: ${new Date().toLocaleDateString()}`, 14, 28);

        // 2. Garis Pemisah
        doc.setLineWidth(0.5);
        doc.line(14, 32, 196, 32);

        // 3. Ringkasan AI (Simulasi)
        doc.setFontSize(12);
        doc.text("Executive Summary:", 14, 40);
        doc.setFontSize(10);
        const summaryText = "Berdasarkan analisis 24 jam terakhir, tingkat kepatuhan APD rata-rata adalah 92%. Terdeteksi lonjakan pelanggaran 'No Helmet' pada pukul 14:00 di Zona A. Direkomendasikan patroli fisik di area Loading Dock.";
        doc.text(doc.splitTextToSize(summaryText, 180), 14, 48);

        // 4. Tabel Pelanggaran
        autoTable(doc, {
            startY: 65,
            head: [['ID', 'Waktu', 'Lokasi', 'Jenis Pelanggaran', 'Status']],
            body: historyData.map(row => [row.id, row.time, row.location, row.type, row.status]),
            theme: 'grid',
            headStyles: { fillColor: [249, 115, 22] }, // Warna Orange SmartAPD
        });

        // 5. Footer
        const pageCount = doc.internal.getNumberOfPages();
        doc.setFontSize(8);
        for (let i = 1; i <= pageCount; i++) {
            doc.setPage(i);
            doc.text('Page ' + String(i) + ' of ' + String(pageCount), 196, 285, { align: 'right' });
            doc.text('SmartAPD - Zero Accident Vision', 14, 285);
        }

        // Save
        doc.save("SmartAPD_Report_Daily.pdf");
        setIsGenerating(false);
    };

    return (
        <div className="space-y-8 p-4 md:p-8 pb-20 min-h-screen bg-slate-950">

            {/* HEADER SECTION */}
            <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-4">
                <div>
                    <h1 className="text-3xl font-black text-white tracking-tight">ANALYTICS & REPORT</h1>
                    <p className="text-slate-400">Analisis K3 berbasis AI dan Laporan Otomatis.</p>
                </div>
                <button
                    onClick={handleDownloadPDF}
                    disabled={isGenerating}
                    className="flex items-center gap-2 px-6 py-3 bg-gradient-to-r from-orange-600 to-orange-500 hover:from-orange-500 hover:to-orange-400 text-white font-bold rounded-xl shadow-lg shadow-orange-500/20 transition-all disabled:opacity-70"
                >
                    {isGenerating ? <Clock className="animate-spin" size={20} /> : <Download size={20} />}
                    {isGenerating ? "Generating..." : "Download Report (PDF)"}
                </button>
            </div>

            {/* KPI CARDS */}
            <div className="grid grid-cols-1 md:grid-cols-4 gap-6">
                <div className="p-6 bg-slate-900/50 border border-slate-800 rounded-3xl backdrop-blur-sm">
                    <div className="flex justify-between items-start mb-4">
                        <div className="p-3 bg-emerald-500/10 rounded-xl text-emerald-500"><CheckCircle /></div>
                        <span className="text-xs font-bold text-emerald-500 bg-emerald-500/10 px-2 py-1 rounded-full">+2.4%</span>
                    </div>
                    <h3 className="text-4xl font-black text-white mb-1">92%</h3>
                    <p className="text-sm text-slate-400 font-medium">Safety Score</p>
                </div>
                <div className="p-6 bg-slate-900/50 border border-slate-800 rounded-3xl backdrop-blur-sm">
                    <div className="flex justify-between items-start mb-4">
                        <div className="p-3 bg-red-500/10 rounded-xl text-red-500"><AlertTriangle /></div>
                        <span className="text-xs font-bold text-red-500 bg-red-500/10 px-2 py-1 rounded-full">+5 New</span>
                    </div>
                    <h3 className="text-4xl font-black text-white mb-1">12</h3>
                    <p className="text-sm text-slate-400 font-medium">Total Pelanggaran</p>
                </div>
                <div className="p-6 bg-slate-900/50 border border-slate-800 rounded-3xl backdrop-blur-sm">
                    <div className="flex justify-between items-start mb-4">
                        <div className="p-3 bg-blue-500/10 rounded-xl text-blue-500"><Clock /></div>
                    </div>
                    <h3 className="text-4xl font-black text-white mb-1">24h</h3>
                    <p className="text-sm text-slate-400 font-medium">Monitoring Time</p>
                </div>
                <div className="p-6 bg-slate-900/50 border border-slate-800 rounded-3xl backdrop-blur-sm">
                    <div className="flex justify-between items-start mb-4">
                        <div className="p-3 bg-orange-500/10 rounded-xl text-orange-500"><ShieldAlert /></div>
                    </div>
                    <h3 className="text-4xl font-black text-white mb-1">3</h3>
                    <p className="text-sm text-slate-400 font-medium">Critical Alerts</p>
                </div>
            </div>

            {/* CHARTS SECTION */}
            <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
                {/* Trend Chart (2 Kolom) */}
                <div className="lg:col-span-2 p-6 bg-slate-900/50 border border-slate-800 rounded-3xl">
                    <h3 className="text-lg font-bold text-white mb-6 flex items-center gap-2"><FileText size={18} className="text-orange-500" /> Tren Kepatuhan (Live)</h3>
                    <div className="h-[300px] w-full">
                        <ResponsiveContainer width="100%" height="100%">
                            <AreaChart data={dataTrend}>
                                <defs>
                                    <linearGradient id="colorScore" x1="0" y1="0" x2="0" y2="1">
                                        <stop offset="5%" stopColor="#10b981" stopOpacity={0.3} />
                                        <stop offset="95%" stopColor="#10b981" stopOpacity={0} />
                                    </linearGradient>
                                </defs>
                                <CartesianGrid strokeDasharray="3 3" stroke="#1e293b" />
                                <XAxis dataKey="time" stroke="#64748b" fontSize={12} />
                                <YAxis stroke="#64748b" fontSize={12} domain={[0, 100]} />
                                <Tooltip contentStyle={{ backgroundColor: '#0f172a', borderColor: '#334155', color: '#fff' }} />
                                <Area type="monotone" dataKey="score" stroke="#10b981" strokeWidth={3} fillOpacity={1} fill="url(#colorScore)" />
                            </AreaChart>
                        </ResponsiveContainer>
                    </div>
                </div>

                {/* Violation Type Chart (1 Kolom) */}
                <div className="p-6 bg-slate-900/50 border border-slate-800 rounded-3xl">
                    <h3 className="text-lg font-bold text-white mb-6">Jenis Pelanggaran</h3>
                    <div className="h-[300px] w-full">
                        <ResponsiveContainer width="100%" height="100%">
                            <BarChart data={dataViolation} layout="vertical">
                                <CartesianGrid strokeDasharray="3 3" horizontal={false} stroke="#1e293b" />
                                <XAxis type="number" stroke="#64748b" hide />
                                <YAxis dataKey="name" type="category" stroke="#94a3b8" width={100} fontSize={12} />
                                <Tooltip contentStyle={{ backgroundColor: '#0f172a', borderColor: '#334155', color: '#fff' }} cursor={{ fill: '#1e293b' }} />
                                <Bar dataKey="count" fill="#f97316" radius={[0, 4, 4, 0]} barSize={20} />
                            </BarChart>
                        </ResponsiveContainer>
                    </div>
                </div>
            </div>

            {/* HISTORY TABLE SECTION */}
            <div className="p-6 bg-slate-900/50 border border-slate-800 rounded-3xl">
                <div className="flex flex-col md:flex-row justify-between items-center mb-6 gap-4">
                    <h3 className="text-lg font-bold text-white flex items-center gap-2"><ShieldAlert size={18} className="text-red-500" /> Riwayat Pelanggaran (Real-time)</h3>
                    <div className="flex gap-2">
                        <button className="px-4 py-2 bg-slate-800 hover:bg-slate-700 text-slate-300 text-sm font-bold rounded-lg flex items-center gap-2"><Filter size={16} /> Filter</button>
                    </div>
                </div>

                <div className="overflow-x-auto">
                    <table className="w-full text-left border-collapse">
                        <thead>
                            <tr className="border-b border-slate-800 text-slate-400 text-sm uppercase tracking-wider">
                                <th className="p-4 font-bold">ID</th>
                                <th className="p-4 font-bold">Waktu</th>
                                <th className="p-4 font-bold">Lokasi</th>
                                <th className="p-4 font-bold">Pelanggaran</th>
                                <th className="p-4 font-bold">Status</th>
                            </tr>
                        </thead>
                        <tbody className="text-slate-200 text-sm">
                            {historyData.map((item, index) => (
                                <tr key={index} className="border-b border-slate-800/50 hover:bg-slate-800/30 transition">
                                    <td className="p-4 font-mono text-slate-500">{item.id}</td>
                                    <td className="p-4">{item.time}</td>
                                    <td className="p-4 font-bold">{item.location}</td>
                                    <td className="p-4">
                                        <span className="flex items-center gap-2">
                                            <AlertTriangle size={14} className="text-orange-500" /> {item.type}
                                        </span>
                                    </td>
                                    <td className="p-4">
                                        <span className={`px-3 py-1 rounded-full text-xs font-bold ${item.status === 'Open'
                                                ? 'bg-red-500/10 text-red-500 border border-red-500/20'
                                                : 'bg-emerald-500/10 text-emerald-500 border border-emerald-500/20'
                                            }`}>
                                            {item.status}
                                        </span>
                                    </td>
                                </tr>
                            ))}
                        </tbody>
                    </table>
                </div>
            </div>

        </div>
    );
}
