import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

// Define the structure of the violation data
export interface ViolationReportData {
  date: string;
  type: string;
  location: string;
  status: 'Open' | 'Resolved' | 'In Progress' | string;
}

/**
 * Generates and downloads a weekly safety report PDF.
 * @param data Array of violation data to be included in the report.
 */
export const downloadWeeklyReport = (data: ViolationReportData[]) => {
  // 1. Initialize jsPDF instance (Portrait, Millimeters, A4)
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4',
  });

  // Define constants for layout
  const pageWidth = doc.internal.pageSize.width;
  const pageHeight = doc.internal.pageSize.height;
  const margin = 14;
  const primaryColor = '#1e3a8a'; // Dark Blue (Professional)
  const secondaryColor = '#64748b'; // Slate Grey

  // --- HEADER SECTION ---
  
  // Draw a colored top bar for branding
  doc.setFillColor(primaryColor);
  doc.rect(0, 0, pageWidth, 25, 'F');

  // Title "Laporan Keselamatan Mingguan" (White text on blue background)
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.text('Laporan Keselamatan Mingguan', margin, 16);

  // Logo / Brand Name "SmartAPD" (Right aligned in the header)
  doc.setFontSize(12);
  doc.setFont('helvetica', 'normal');
  doc.text('SmartAPD AI System', pageWidth - margin, 16, { align: 'right' });

  // Sub-header info (Date Generated) underneath the blue bar
  const today = new Date().toLocaleDateString('id-ID', {
    weekday: 'long',
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });
  
  doc.setTextColor(secondaryColor);
  doc.setFontSize(10);
  doc.text(`Tanggal Generate: ${today}`, margin, 32);

  // --- TABLE CONTENT ---

  // Prepare table data
  const tableColumn = ['No', 'Tanggal', 'Jenis Pelanggaran', 'Lokasi', 'Status'];
  const tableRows = data.map((item, index) => [
    index + 1,
    item.date,
    item.type,
    item.location,
    item.status,
  ]);

  // Generate AutoTable
  autoTable(doc, {
    startY: 40,
    head: [tableColumn],
    body: tableRows,
    theme: 'striped',
    headStyles: {
      fillColor: primaryColor,
      textColor: [255, 255, 255],
      fontStyle: 'bold',
      halign: 'center',
    },
    bodyStyles: {
      textColor: [50, 50, 50],
    },
    alternateRowStyles: {
      fillColor: [245, 247, 250],
    },
    columnStyles: {
      0: { halign: 'center', cellWidth: 15 }, // No
      1: { cellWidth: 40 }, // Tanggal
      2: { cellWidth: 'auto' }, // Jenis
      3: { cellWidth: 40 }, // Lokasi
      4: { halign: 'center', cellWidth: 30 }, // Status
    },
    // Add footer to each page
    didDrawPage: (data) => {
      // Footer text
      const footerText = 'Generated by SmartAPD AI System';
      const timestamp = new Date().toLocaleString('id-ID');
      const pageNumber = `Halaman ${doc.getNumberOfPages()}`;

      doc.setFontSize(8);
      doc.setTextColor(150, 150, 150); // Light grey

      // Bottom Left: System Name
      doc.text(footerText, margin, pageHeight - 10);

      // Bottom Center: Timestamp
      doc.text(timestamp, pageWidth / 2, pageHeight - 10, { align: 'center' });

      // Bottom Right: Page Number
      doc.text(pageNumber, pageWidth - margin, pageHeight - 10, { align: 'right' });
    },
  });

  // --- SAVE FILE ---
  // Format filename with timestamp: Safety_Report_YYYY-MM-DD.pdf
  const dateStr = new Date().toISOString().split('T')[0];
  doc.save(`SmartAPD_Report_${dateStr}.pdf`);
};
